#!/usr/bin/env python3
# SPDX-License-Identifier: OAI-OpenAirInterface
#
# Compare two machine-readable L1_TX_JOB_DL JSON summaries generated by:
#   analyze_l1tx_capture.py --json-summary

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, Optional


EXPECTED_SCHEMA = "rt_deadline_l1tx_summary.v1"


def load_summary(path: Path) -> Dict[str, Any]:
    with path.open(encoding="utf-8") as f:
        data = json.load(f)

    schema = data.get("schema")
    if schema != EXPECTED_SCHEMA:
        raise ValueError(
            f"{path}: unsupported schema {schema!r}, expected {EXPECTED_SCHEMA!r}"
        )

    return data


def get_nested(data: Dict[str, Any], dotted_key: str) -> Optional[Any]:
    current: Any = data
    for part in dotted_key.split("."):
        if not isinstance(current, dict) or part not in current:
            return None
        current = current[part]
    return current


def fmt_value(value: Any) -> str:
    if value is None:
        return "NA"
    if isinstance(value, float):
        return f"{value:.3f}"
    return str(value)


def delta(candidate: Any, baseline: Any) -> Optional[float]:
    if not isinstance(candidate, (int, float)):
        return None
    if not isinstance(baseline, (int, float)):
        return None
    return float(candidate) - float(baseline)


def ratio(candidate: Any, baseline: Any) -> Optional[float]:
    if not isinstance(candidate, (int, float)):
        return None
    if not isinstance(baseline, (int, float)):
        return None
    if baseline == 0:
        return None
    return float(candidate) / float(baseline)


def print_metric(label: str, baseline: Any, candidate: Any) -> None:
    d = delta(candidate, baseline)
    r = ratio(candidate, baseline)

    fields = [
        "metric",
        f"name={label}",
        f"baseline={fmt_value(baseline)}",
        f"candidate={fmt_value(candidate)}",
    ]

    if d is not None:
        fields.append(f"delta={d:.3f}")
    else:
        fields.append("delta=NA")

    if r is not None:
        fields.append(f"ratio={r:.3f}")
    else:
        fields.append("ratio=NA")

    print(" ".join(fields))


def bucket_count(data: Dict[str, Any], bucket: str) -> Optional[Any]:
    return get_nested(data, f"duration_unit.buckets.{bucket}.count")


def context_count(data: Dict[str, Any], context_kind: str, bucket: str) -> Optional[Any]:
    if context_kind == "valid":
        return get_nested(data, f"context.valid_duration_unit.buckets.{bucket}.count")
    if context_kind == "invalid":
        return get_nested(data, f"context.invalid_duration_unit.buckets.{bucket}.count")
    return None


def threshold_count(data: Dict[str, Any], threshold_us: int) -> Optional[Any]:
    thresholds = data.get("thresholds")
    if not isinstance(thresholds, list):
        return None

    for item in thresholds:
        if isinstance(item, dict) and item.get("threshold_us") == threshold_us:
            return item.get("count")

    return None


def compare_summaries(
    baseline: Dict[str, Any],
    candidate: Dict[str, Any],
    baseline_name: str,
    candidate_name: str,
) -> None:
    print("RT_DEADLINE_L1TX_COMPARE")
    print(f"baseline_name={baseline_name}")
    print(f"candidate_name={candidate_name}")
    print(f"baseline_csv={baseline.get('csv_path', 'NA')}")
    print(f"candidate_csv={candidate.get('csv_path', 'NA')}")

    baseline_unit = get_nested(baseline, "duration_unit.unit_name")
    candidate_unit = get_nested(candidate, "duration_unit.unit_name")
    baseline_unit_us = get_nested(baseline, "duration_unit.unit_us")
    candidate_unit_us = get_nested(candidate, "duration_unit.unit_us")

    print(f"baseline_unit={fmt_value(baseline_unit)}")
    print(f"candidate_unit={fmt_value(candidate_unit)}")
    print(f"baseline_unit_us={fmt_value(baseline_unit_us)}")
    print(f"candidate_unit_us={fmt_value(candidate_unit_us)}")

    if baseline_unit != candidate_unit or baseline_unit_us != candidate_unit_us:
        print("warning=duration_unit_mismatch")

    metric_keys = [
        "samples",
        "min_us",
        "avg_us",
        "max_us",
        "p50_us",
        "p90_us",
        "p99_us",
        "p999_us",
        "p9999_us",
        "late_count",
        "late_ratio_ppm",
    ]

    for key in metric_keys:
        print_metric(key, baseline.get(key), candidate.get(key))

    for threshold_us in [200, 500, 1000, 2000]:
        print_metric(
            f"over_{threshold_us}_us",
            threshold_count(baseline, threshold_us),
            threshold_count(candidate, threshold_us),
        )

    for bucket in ["le_1", "gt_1_le_2", "gt_2_le_3", "gt_3"]:
        print_metric(
            f"bucket_{bucket}",
            bucket_count(baseline, bucket),
            bucket_count(candidate, bucket),
        )

    for context_kind in ["valid", "invalid"]:
        for bucket in ["le_1", "gt_1_le_2", "gt_2_le_3", "gt_3"]:
            print_metric(
                f"context_{context_kind}_bucket_{bucket}",
                context_count(baseline, context_kind, bucket),
                context_count(candidate, context_kind, bucket),
            )

    baseline_warnings = baseline.get("warnings", [])
    candidate_warnings = candidate.get("warnings", [])

    print(f"baseline_warning_count={len(baseline_warnings)}")
    print(f"candidate_warning_count={len(candidate_warnings)}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compare two L1_TX_JOB_DL JSON summaries."
    )
    parser.add_argument(
        "--baseline",
        type=Path,
        required=True,
        help="Baseline JSON summary generated by analyze_l1tx_capture.py.",
    )
    parser.add_argument(
        "--candidate",
        type=Path,
        required=True,
        help="Candidate/stress JSON summary generated by analyze_l1tx_capture.py.",
    )
    parser.add_argument(
        "--baseline-name",
        default="baseline",
        help="Human-readable name for the baseline run.",
    )
    parser.add_argument(
        "--candidate-name",
        default="candidate",
        help="Human-readable name for the candidate run.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    try:
        baseline = load_summary(args.baseline)
        candidate = load_summary(args.candidate)
        compare_summaries(
            baseline,
            candidate,
            args.baseline_name,
            args.candidate_name,
        )
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
