# SPDX-License-Identifier: LicenseRef-CSSL-1.0

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(OAI_RISCV_TOOLCHAIN_PREFIX "riscv64-linux-gnu" CACHE STRING "RISC-V GNU toolchain prefix")
set(OAI_RISCV_C_COMPILER "${OAI_RISCV_TOOLCHAIN_PREFIX}-gcc" CACHE FILEPATH "RISC-V C compiler")
set(OAI_RISCV_CXX_COMPILER "${OAI_RISCV_TOOLCHAIN_PREFIX}-g++" CACHE FILEPATH "RISC-V C++ compiler")

if(NOT IS_ABSOLUTE "${OAI_RISCV_C_COMPILER}")
  find_program(_OAI_RISCV_C_COMPILER_PATH
    NAMES ${OAI_RISCV_C_COMPILER}
    HINTS "$ENV{HOME}/opt/toolchains/spacemit-riscv/bin")
  if(_OAI_RISCV_C_COMPILER_PATH)
    set(OAI_RISCV_C_COMPILER "${_OAI_RISCV_C_COMPILER_PATH}" CACHE FILEPATH "RISC-V C compiler" FORCE)
  endif()
endif()

if(NOT IS_ABSOLUTE "${OAI_RISCV_CXX_COMPILER}")
  find_program(_OAI_RISCV_CXX_COMPILER_PATH
    NAMES ${OAI_RISCV_CXX_COMPILER}
    HINTS "$ENV{HOME}/opt/toolchains/spacemit-riscv/bin")
  if(_OAI_RISCV_CXX_COMPILER_PATH)
    set(OAI_RISCV_CXX_COMPILER "${_OAI_RISCV_CXX_COMPILER_PATH}" CACHE FILEPATH "RISC-V C++ compiler" FORCE)
  endif()
endif()

set(CMAKE_C_COMPILER   ${OAI_RISCV_C_COMPILER})
set(CMAKE_CXX_COMPILER ${OAI_RISCV_CXX_COMPILER})

if(DEFINED ENV{K3_SYSROOT})
  set(_OAI_RISCV_SYSROOT_DEFAULT "$ENV{K3_SYSROOT}")
elseif(DEFINED ENV{RISCV_SYSROOT})
  set(_OAI_RISCV_SYSROOT_DEFAULT "$ENV{RISCV_SYSROOT}")
elseif(DEFINED ENV{HOME})
  set(_OAI_RISCV_SYSROOT_DEFAULT "$ENV{HOME}/sysroots/k3")
else()
  set(_OAI_RISCV_SYSROOT_DEFAULT "/home/jovyan/sysroots/k3")
endif()

set(OAI_RISCV_SYSROOT "${_OAI_RISCV_SYSROOT_DEFAULT}" CACHE PATH "RISC-V target sysroot")
if(NOT EXISTS "${OAI_RISCV_SYSROOT}")
  message(FATAL_ERROR "OAI_RISCV_SYSROOT '${OAI_RISCV_SYSROOT}' does not exist; set K3_SYSROOT, RISCV_SYSROOT, or -DOAI_RISCV_SYSROOT")
endif()
set(CMAKE_SYSROOT ${OAI_RISCV_SYSROOT})
set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# The K3 Debian/Bianbu sysroot stores glibc headers, startup objects, and
# libraries in Debian multiarch directories, while SpaceMIT GCC searches the
# generic usr/include and usr/lib directories by default.
set(OAI_RISCV_SYSROOT_MULTIARCH "riscv64-linux-gnu" CACHE STRING "RISC-V sysroot multiarch directory")
set(OAI_RISCV_SYSROOT_INCLUDEDIR "${CMAKE_SYSROOT}/usr/include/${OAI_RISCV_SYSROOT_MULTIARCH}" CACHE PATH "RISC-V sysroot include directory")
set(OAI_RISCV_SYSROOT_LIBDIR "${CMAKE_SYSROOT}/usr/lib/${OAI_RISCV_SYSROOT_MULTIARCH}" CACHE PATH "RISC-V sysroot library directory")
set(CMAKE_LIBRARY_ARCHITECTURE ${OAI_RISCV_SYSROOT_MULTIARCH})
if(EXISTS "${OAI_RISCV_SYSROOT_INCLUDEDIR}")
  set(CMAKE_C_FLAGS_INIT "-isystem${OAI_RISCV_SYSROOT_INCLUDEDIR} ${CMAKE_C_FLAGS_INIT}")
  set(CMAKE_CXX_FLAGS_INIT "-isystem${OAI_RISCV_SYSROOT_INCLUDEDIR} ${CMAKE_CXX_FLAGS_INIT}")
endif()
if(EXISTS "${OAI_RISCV_SYSROOT_LIBDIR}")
  set(CMAKE_C_FLAGS_INIT "-B${OAI_RISCV_SYSROOT_LIBDIR} ${CMAKE_C_FLAGS_INIT}")
  set(CMAKE_CXX_FLAGS_INIT "-B${OAI_RISCV_SYSROOT_LIBDIR} ${CMAKE_CXX_FLAGS_INIT}")
  set(CMAKE_EXE_LINKER_FLAGS_INIT "-B${OAI_RISCV_SYSROOT_LIBDIR} -L${OAI_RISCV_SYSROOT_LIBDIR} ${CMAKE_EXE_LINKER_FLAGS_INIT}")
  set(CMAKE_SHARED_LINKER_FLAGS_INIT "-L${OAI_RISCV_SYSROOT_LIBDIR} ${CMAKE_SHARED_LINKER_FLAGS_INIT}")
  set(CMAKE_MODULE_LINKER_FLAGS_INIT "-L${OAI_RISCV_SYSROOT_LIBDIR} ${CMAKE_MODULE_LINKER_FLAGS_INIT}")
endif()

set(ENV{PKG_CONFIG_SYSROOT_DIR} "${CMAKE_SYSROOT}")
set(ENV{PKG_CONFIG_LIBDIR} "${CMAKE_SYSROOT}/usr/lib/riscv64-linux-gnu/pkgconfig:${CMAKE_SYSROOT}/usr/lib/pkgconfig:${CMAKE_SYSROOT}/usr/share/pkgconfig")

set(CROSS_COMPILE 1)
set(bnProc_gen_128_DIR    ${CMAKE_CURRENT_BINARY_DIR}/${NATIVE_DIR}) # /../build)
set(bnProc_gen_avx2_DIR   ${CMAKE_CURRENT_BINARY_DIR}/${NATIVE_DIR}) # /../build)
set(bnProc_gen_avx512_DIR ${CMAKE_CURRENT_BINARY_DIR}/${NATIVE_DIR}) # /../build)
set(cnProc_gen_128_DIR    ${CMAKE_CURRENT_BINARY_DIR}/${NATIVE_DIR}) # /../build)
set(cnProc_gen_avx2_DIR   ${CMAKE_CURRENT_BINARY_DIR}/${NATIVE_DIR}) # /../build)
set(cnProc_gen_avx512_DIR ${CMAKE_CURRENT_BINARY_DIR}/${NATIVE_DIR}) # /../build)
set(genids_DIR            ${CMAKE_CURRENT_BINARY_DIR}/${NATIVE_DIR}) # /../build)
set(_check_vcd_DIR        ${CMAKE_CURRENT_BINARY_DIR}/${NATIVE_DIR}) # /../build)
