/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

#ifndef __TIME_MEAS__H__
#define __TIME_MEAS__H__

#include <unistd.h>
#include <math.h>
#include <stdint.h>
#include <time.h>
#include <errno.h>
#include <stdio.h>
#include <pthread.h>
#include <linux/kernel.h>
#include <linux/types.h>
#include "common/utils/time_meas_defs.h"
// global var to enable openair performance profiler
extern int cpu_meas_enabled;
extern double cpu_freq_GHz  __attribute__ ((aligned(32)));
// structure to store data to compute cpu measurment
#if defined(__x86_64__) || defined(__i386__) || defined(__arm__) || defined(__aarch64__)
  typedef long long oai_cputime_t;
#else
  #error "building on unsupported CPU architecture"
#endif

#define TIMESTAT_MSGID_START       0     /*!< \brief send time at measure starting point */
#define TIMESTAT_MSGID_STOP        1     /*!< \brief send time at measure end  point */
#define TIMESTAT_MSGID_ENABLE      2     /*!< \brief enable measure point */
#define TIMESTAT_MSGID_DISABLE     3     /*!< \brief disable measure point */
#define TIMESTAT_MSGID_DISPLAY     10    /*!< \brief display measure */
#define TIMESTAT_MSGID_END         11    /*!< \brief stops the measure threads and free assocated resources */
typedef void(*meas_printfunc_t)(const char* format, ...);
typedef struct {
  int               msgid;                  /*!< \brief message id, as defined by TIMESTAT_MSGID_X macros */
  int               timestat_id;            /*!< \brief points to the time_stats_t entry in cpumeas table */
  oai_cputime_t  ts;                        /*!< \brief time stamp */
  meas_printfunc_t  displayFunc;            /*!< \brief function to call when DISPLAY message is received*/
} time_stats_msg_t;

/**
 * TIME_MEAS_HISTOGRAM_BIN_WIDTH_NS,
 * TIME_MEAS_HISTOGRAM_SPAN_NS and
 * TIME_MEAS_HISTOGRAM_NUM_BINS
 * are defined in time_meas_defs.h
 * which is generated by cmake from
 * time_meas_defs.h.in with default
 * values from the CMakeLists.txt
 */
typedef struct {
  uint64_t counts[TIME_MEAS_HISTOGRAM_NUM_BINS];
  uint64_t out_of_range;
} time_hist_t;

/**
 * \brief resets histogram (clears all counts)
 * \param hist histogram to be reset
 */
void reset_time_hist(time_hist_t *hist);

/**
 * \brief inserts value into histogram
 * if value is out of range, it is dropped
 * \param hist histogram to insert in
 * \param time time value to insert in nanoseconds
 */
void insert_in_time_hist(time_hist_t *hist, oai_cputime_t time);

/**
 * \brief copy histogram src into dst
 * \param dst destination histogram
 * \param src source histogram
 */
void copy_time_hist(time_hist_t *dst, const time_hist_t *src);

/**
 * \brief merges histogram src into dst
 * \param dst destination histogram
 * \param src source histogram
 */
void merge_time_hist(time_hist_t *dst, const time_hist_t *src);

/**
 * \brief get the minimum from a histogram
 * returns 0 if no entries, otherwise the lower bound of the first non-empty bin
 * \param hist histogram to query
 */
oai_cputime_t get_min(time_hist_t *hist);

/**
 * \brief get the median from a histogram
 * returns 0 if no entries, otherwise an approximation from the histogram
 * \param hist histogram to query
 */
oai_cputime_t get_median(time_hist_t *hist);

/**
 * \brief get the first quartile from a histogram
 * returns 0 if no entries, otherwise an approximation from the histogram
 * \param hist histogram to query
 */
oai_cputime_t get_q1(time_hist_t *hist);

/**
 * \brief get the third quartile from a histogram
 * returns 0 if no entries, otherwise an approximation from the histogram
 * \param hist histogram to query
 */
oai_cputime_t get_q3(time_hist_t *hist);

/**
 * \brief get the first decile from a histogram
 * returns 0 if no entries, otherwise an approximation from the histogram
 * \param hist histogram to query
 */
oai_cputime_t get_d1(time_hist_t *hist);

/**
 * \brief get the nineth decile from a histogram
 * returns 0 if no entries, otherwise an approximation from the histogram
 * \param hist histogram to query
 */
oai_cputime_t get_d9(time_hist_t *hist);

struct notifiedFIFO_elt_s;
typedef struct time_stats {
  oai_cputime_t in;                                /*!< \brief time at measure starting point */
  oai_cputime_t diff;                              /*!< \brief average difference between time at starting point and time at endpoint*/
  oai_cputime_t p_time;                            /*!< \brief absolute process duration */
  double diff_square;                              /*!< \brief process duration square */
  oai_cputime_t max;                               /*!< \brief maximum difference between time at starting point and time at endpoint*/
  int trials;                                      /*!< \brief number of start point - end point iterations */
  int meas_flag;                                   /*!< \brief 1: stop_meas not called (consecutive calls of start_meas) */
  char *meas_name;                                 /*!< \brief name to use when printing the measure (not used for PHY simulators)*/
  int meas_index;                                  /*!< \brief index of this measure in the measure array (not used for PHY simulators)*/
  int meas_enabled;                                /*!< \brief per measure enablement flag. send_meas tests this flag, unused today in start_meas and stop_meas*/
  struct notifiedFIFO_elt_s *tpoolmsg;             /*!< \brief message pushed to the cpu measurment queue to report a measure START or STOP */
  time_stats_msg_t *tstatptr;                      /*!< \brief pointer to the time_stats_msg_t data in the tpoolmsg, stored here for perf considerations */
  time_hist_t time_hist;     /*!< \brief histogram to get time distribution */
} time_stats_t;
#define MEASURE_ENABLED(X)       (X->meas_enabled)

static inline void start_meas(time_stats_t *ts) __attribute__((always_inline));
static inline void stop_meas(time_stats_t *ts) __attribute__((always_inline));

/**
 * \struct time_single
 * \brief same as time_stats but lighter and for a single measure to merge in a time_stats
 */
typedef struct time_single {
  oai_cputime_t in;                                /*!< \brief time at measure starting point */
  oai_cputime_t p_time;                            /*!< \brief absolute process duration */
} time_single_t;

static inline void start_single_meas(time_single_t *ts) __attribute__((always_inline));
static inline void stop_single_meas(time_single_t *ts) __attribute__((always_inline));

/**
 * \brief get the standard deviation of a timer
 * \param ptr timer to query
 */
double get_std_dev(time_stats_t *ptr);
void print_meas_now(time_stats_t *ts, const char *name, FILE *file_name);
void print_meas(time_stats_t *ts, const char *name, time_stats_t *total_exec_time, time_stats_t *sf_exec_time);
size_t print_meas_log_header(time_stats_t *total_exec_time,
                             time_stats_t *sf_exec_time,
                             char *output,
                             size_t outputlen,
                             int cpu_meas_enabled);
size_t print_meas_log(time_stats_t *ts,
                      const char *name,
                      time_stats_t *total_exec_time,
                      time_stats_t *sf_exec_time,
                      char *output,
                      size_t outputlen);
double get_time_meas_us(time_stats_t *ts);
double get_cpu_freq_GHz(void);

#if defined(__i386__)
static inline unsigned long long rdtsc_oai(void) __attribute__((always_inline));
static inline unsigned long long rdtsc_oai(void) {
  unsigned long long int x;
  __asm__ volatile (".byte 0x0f, 0x31" : "=A" (x));
  return x;
}
#elif defined(__x86_64__)
static inline unsigned long long rdtsc_oai(void) __attribute__((always_inline));
static inline unsigned long long rdtsc_oai(void) {
  unsigned long long a, d;
  __asm__ volatile ("rdtsc" : "=a" (a), "=d" (d));
  return (d<<32) | a;
}
#elif defined(__aarch64__)
static inline uint64_t rdtsc_oai(void) __attribute__((always_inline));
static inline uint64_t rdtsc_oai(void)
{
	  uint64_t r = 0;
	    asm volatile("mrs %0, cntvct_el0" : "=r"(r));
	      return r;
}

#elif defined(__arm__) 
static inline uint32_t rdtsc_oai(void) __attribute__((always_inline));
static inline uint32_t rdtsc_oai(void) {
  uint32_t r = 0;
  asm volatile("mrc p15, 0, %0, c9, c13, 0" : "=r"(r) );
  return r;
}
#endif

static inline long long clock_gettime_oai()
{
  struct timespec time;
#ifdef CLOCK_MONOTONIC_RAW
  // CLOCK_MONOTONIC_RAW only on linux
  // See clock_getres(2)
  clock_gettime(CLOCK_MONOTONIC_RAW, &time);
#else
  clock_gettime(CLOCK_REALTIME, &time);
#endif
  return 1e+9 * time.tv_sec + time.tv_nsec;
}

#define CPUMEAS_DISABLE  0
#define CPUMEAS_ENABLE   1
#define CPUMEAS_GETSTATE 2
static inline int cpumeas(int action) {
  switch (action) {
    case CPUMEAS_ENABLE:
      cpu_meas_enabled = 1;
      break;

    case CPUMEAS_DISABLE:
      cpu_meas_enabled = 0;
      break;

    case CPUMEAS_GETSTATE:
    default:
      break;
  }

  return cpu_meas_enabled;
}

static inline void start_meas(time_stats_t *ts) {
  if (cpu_meas_enabled) {
    if (ts->meas_flag==0) {
      ts->trials++;
      ts->in = clock_gettime_oai();
      ts->meas_flag=1;
    } else {
      ts->in = clock_gettime_oai();
    }
    if ((ts->trials&16383)<10) ts->max=0;
  }
}

static inline void stop_meas(time_stats_t *ts) {
  if (cpu_meas_enabled) {
    long long out = clock_gettime_oai();
    if (ts->in) {
      ts->diff += (out - ts->in);
      /// process duration is the difference between two clock points
      ts->p_time = (out - ts->in);
      ts->diff_square += ((double)out - ts->in) * ((double)out - ts->in);

      if ((out - ts->in) > ts->max)
        ts->max = out - ts->in;

      insert_in_time_hist(&ts->time_hist, (out - ts->in));
      ts->meas_flag = 0;
    }
  }
}

static inline void start_single_meas(time_single_t *ts) {
  if (cpu_meas_enabled) {
    ts->in = clock_gettime_oai();
  }
}

static inline void stop_single_meas(time_single_t *ts) {
  if (cpu_meas_enabled) {
    long long out = clock_gettime_oai();
    if (ts->in) {
      /// process duration is the difference between two clock points
      ts->p_time = (out - ts->in);
    }
  }
}

static inline void reset_meas(time_stats_t *ts) {
  ts->in=0;
  ts->diff=0;
  ts->p_time=0;
  ts->diff_square=0;
  ts->max=0;
  ts->trials=0;
  ts->meas_flag=0;
  reset_time_hist(&ts->time_hist);
}

static inline void reset_single_meas(time_single_t *ts) {
  ts->in=0;
  ts->p_time=0;
}

static inline void copy_meas(time_stats_t *dst_ts,time_stats_t *src_ts) {
  if (cpu_meas_enabled) {
    dst_ts->trials=src_ts->trials;
    dst_ts->diff=src_ts->diff;
    dst_ts->max=src_ts->max;
    copy_time_hist(&dst_ts->time_hist, &src_ts->time_hist);
  }
}

static inline void merge_meas(time_stats_t *dst_ts, const time_stats_t *src_ts)
{
  if (!cpu_meas_enabled)
    return;
  dst_ts->trials += src_ts->trials;
  dst_ts->diff += src_ts->diff;
  dst_ts->diff_square += src_ts->diff_square;
  if (src_ts->max > dst_ts->max)
    dst_ts->max = src_ts->max;
  merge_time_hist(&dst_ts->time_hist, &src_ts->time_hist);
}

/**
 * \brief merge single measurement in time_stats
 * \param dst_ts time_stats to merge into
 * \param src_ts single measurement to merge
 */
static inline void merge_single_meas(time_stats_t *dst_ts, const time_single_t *src_ts)
{
  if (!cpu_meas_enabled)
    return;
  dst_ts->trials += 1;
  dst_ts->diff += src_ts->p_time;
  dst_ts->diff_square += src_ts->p_time * src_ts->p_time;
  if (src_ts->p_time > dst_ts->max)
    dst_ts->max = src_ts->p_time;
  insert_in_time_hist(&dst_ts->time_hist, src_ts->p_time);
}

#define TIME_STATS_ACCUMULATE_MODE 1 // cpu_meas_enabled == 1 => accumulate through time
#define TIME_STATS_INSTANT_MODE 2 // cpu_meas_enabled == 2 => reset every second

#define CPUMEASUR_SECTION "cpumeasur"

// clang-format off
#define CPUMEASUR_PARAMS_DESC { \
  {"max_cpumeasur",     "Max number of cpu measur entries",      0,       .uptr=&max_cpumeasur,           .defintval=100,         TYPE_UINT,   0}, \
}
// clang-format on

void init_meas(void);
time_stats_t *register_meas(char *name);
#define START_MEAS(X) send_meas(X, TIMESTAT_MSGID_START)
#define STOP_MEAS(X)  send_meas(X, TIMESTAT_MSGID_STOP)
void send_meas(time_stats_t *ts, int msgid);
void end_meas(void);

#define timeIt(a)                                           \
  {                                                         \
    uint64_t deb = clock_gettime_oai();                             \
    a;                                                      \
    LOG_W(UTIL, #a ": %llu\n", (clock_gettime_oai() - deb) / 3000); \
  }
#endif /* __TIME_MEAS__H__ */
